server:
  port: 8877

spring:
  redis:
    host: 173.249.206.87
    port: 6379
    password: jhkdjhkjdhsIUTYURTU_p6ekja
    database: 1

websocket:
  enable: true
  port: 8878

tcpsocket:
  enable: false # 暂时不开启
  port: 8879

jwt:
  accessToken:
    secret: MIIBIjANBgkq  # 跟im-platfrom的secret必须一致